version: '3.8'

services:
  myapp:
    build: .
    container_name: app_user_service
    ports:
      - 8081:5000
    environment:
      MYSQL_HOST: 'database'
      MYSQL_PORT: 3306
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'book_boutique'
    depends_on:
      - database
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8082:80"
    depends_on:
      - database

  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'book_boutique'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3200:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file=/docker-entrypoint-initdb.d/init.sql --bind-address=0.0.0.0

# Names our volume
volumes:
  mysql_data:
