apiVersion: v1
kind: Namespace
metadata:
  name: book-namespace

# app_product_service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: book-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: lalitbits2023/scalable:product7
          env:
            - name: MYSQL_HOST
              value: '10.102.123.214'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'book_db'
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  namespace: book-namespace
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort    

# app_order_service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: book-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: lalitbits2023/scalable:order8
          env:
            - name: MYSQL_HOST
              value: '10.102.123.214'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'book_db'
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  namespace: book-namespace
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort


# app_cart_service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  namespace: book-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service-container
          image: lalitbits2023/scalable:cart6
          env:
            - name: MYSQL_HOST
              value: '10.101.106.176'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'book_cart_db'
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service-service
  namespace: book-namespace
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  

    
# app_user_service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: book-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: saktib/app_user_service:1.0
          env:
            - name: MYSQL_HOST
              value: '10.108.163.52'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'book_user_db'
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: book-namespace
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort